server:
  port: 8700

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: catalogo
          uri: lb://catalogo-produtos
          predicates:
            - Path=/produtos/**
        - id: pedidos
          uri: lb://simulador-pedidos
          predicates:
            - Path=/pedidos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
